'use client'
/**
 * loadHealthEngine.ts — DispatchOps AI v2
 *
 * Predictive failure analysis & recovery coordination engine.
 * Scores every active load on four dimensions, derives a composite
 * health score, detects stalls in real-time, and surfaces recovery windows
 * before a service failure occurs.
 *
 * TWO-TRACK SEPARATION — identical principle as recoveryEngine:
 *   Compliance Layer  → HOS feasibility score is INFORMATIONAL (mirrors
 *                        HOSDisplay data; never modifies the HOS record).
 *   Operational Layer → stall detection, ETA confidence, weather exposure,
 *                        exception timeline, recovery windows.
 *
 * LS keys:
 *   3b-load-health        — LoadHealthSnapshot[]   (max 100 — one per load)
 *   3b-exception-timeline — ExceptionEvent[]       (max 500)
 *   3b-stall-state        — StallState{}            (keyed by loadNumber)
 */

import {
  readDriverUpdates,
  readDispatchAlerts,
  readEscalations,
  type Severity,
} from '@/lib/dispatchEngine'
import { logLoadHealthEvent, logOpsEvent } from '@/lib/opsEventLog'

// ── Health status tiers ───────────────────────────────────────────────────────

export type LoadHealthStatus = 'healthy' | 'monitor' | 'at_risk' | 'critical'

export const HEALTH_STATUS_META: Record<LoadHealthStatus, {
  label: string; color: string; bg: string; border: string; emoji: string
}> = {
  healthy:  { label: 'On Track',          color: 'var(--primary)', bg: 'rgba(0,232,176,.07)',  border: 'rgba(0,232,176,.25)',  emoji: '✅' },
  monitor:  { label: 'Monitor',           color: 'var(--warn)',    bg: 'rgba(245,194,0,.07)',  border: 'rgba(245,194,0,.25)',  emoji: '👁' },
  at_risk:  { label: 'At Risk',           color: 'var(--warn)',    bg: 'rgba(245,194,0,.1)',   border: 'rgba(245,194,0,.35)',  emoji: '⚠️' },
  critical: { label: 'Critical — Act Now',color: 'var(--error)',   bg: 'rgba(232,64,0,.1)',    border: 'rgba(232,64,0,.4)',    emoji: '🚨' },
}

// ── Stall risk tiers ──────────────────────────────────────────────────────────

export type StallRiskLevel = 'green' | 'yellow' | 'orange' | 'red'

export const STALL_META: Record<StallRiskLevel, {
  label: string; color: string; bg: string; border: string; emoji: string
  description: string
}> = {
  green:  {
    label: 'Active',          emoji: '🟢',
    color: 'var(--primary)',  bg: 'rgba(0,232,176,.06)',  border: 'rgba(0,232,176,.2)',
    description: 'Recent update within 20 min — load progressing normally',
  },
  yellow: {
    label: 'Watch',           emoji: '🟡',
    color: 'var(--warn)',     bg: 'rgba(245,194,0,.07)',  border: 'rgba(245,194,0,.25)',
    description: '20–30 min since last update — monitor for movement',
  },
  orange: {
    label: 'Stall Likely',    emoji: '🟠',
    color: '#f97316',         bg: 'rgba(249,115,22,.08)', border: 'rgba(249,115,22,.3)',
    description: '30–60 min with no update — potential stall situation',
  },
  red:    {
    label: 'Stall Confirmed', emoji: '🔴',
    color: 'var(--error)',    bg: 'rgba(232,64,0,.1)',    border: 'rgba(232,64,0,.4)',
    description: '60+ min with no update or ETA slip >90 min — intervention required',
  },
}

// ── Risk flags ────────────────────────────────────────────────────────────────

export type RiskFlagType =
  | 'eta_slip'
  | 'eta_slip_major'
  | 'hos_critical'
  | 'hos_risk'
  | 'stall_yellow'
  | 'stall_orange'
  | 'stall_red'
  | 'weather_severe'
  | 'weather_wind'
  | 'no_updates'
  | 'detention_running'
  | 'pm_due'
  | 'escalation_critical'
  | 'escalation_warning'
  | 'hos_infeasible'

export interface RiskFlag {
  type:     RiskFlagType
  label:    string
  severity: Severity
  value?:   string    // human-readable context — e.g. "42 min ago", "3.2h HOS"
}

// ── Recovery windows ──────────────────────────────────────────────────────────

export type RecoveryActionType =
  | 'rest_stop'
  | 'reroute'
  | 'reassign'
  | 'extend_delivery'
  | 'contact_customer'
  | 'contact_driver'
  | 'schedule_repair'
  | 'split_load'

export interface RecoveryWindow {
  type:            RecoveryActionType
  title:           string
  description:     string
  urgencyMins:     number    // act within this many minutes
  autoResolvable:  boolean   // AI can suggest exact action vs requires human
  priority:        number    // lower = act first
}

// ── Exception events ──────────────────────────────────────────────────────────

export interface ExceptionEvent {
  id:          string
  loadNumber:  string
  type:        RiskFlagType
  title:       string
  body:        string
  timestamp:   string     // ISO
  resolvedAt?: string
  resolution?: string
  escalated:   boolean
  autoGenerated: boolean
}

// ── Load health snapshot ──────────────────────────────────────────────────────

export interface LoadHealthScore {
  loadNumber:       string
  // Sub-scores (0-100, higher = better)
  etaConfidence:    number   // how likely is on-time delivery
  legalCompletion:  number   // HOS feasibility to complete legally
  weatherExposure:  number   // 100 = clear, 0 = severe storm
  movementScore:    number   // recency of driver updates
  // Composite
  overall:          number   // weighted composite
  status:           LoadHealthStatus
  // Stall detection
  stallRisk:        StallRiskLevel
  stallMinutes:     number   // min since last update or movement event
  // Analytical outputs
  riskFlags:        RiskFlag[]
  recoveryWindows:  RecoveryWindow[]
  // ETA analysis
  etaSlipMins:      number
  projectedArrival: string | null   // our re-estimate vs estArrival
  // Metadata
  snapshot:         string   // ISO — when this was computed
}

// ── Stall state (persisted timer origin) ─────────────────────────────────────

export interface StallState {
  loadNumber:    string
  lastUpdateAt:  string     // ISO of last DriverUpdate
  stallAlertedAt?: string   // when we first surfaced a red-level stall
}

// ── LS keys ───────────────────────────────────────────────────────────────────

const LS_HEALTH     = '3b-load-health'
const LS_EXCEPTIONS = '3b-exception-timeline'
const LS_STALL      = '3b-stall-state'

const MAX_HEALTH     = 100
const MAX_EXCEPTIONS = 500

// ── Stall state helpers ───────────────────────────────────────────────────────

export function readStallStates(): Record<string, StallState> {
  try { return JSON.parse(localStorage.getItem(LS_STALL) ?? '{}') }
  catch { return {} }
}

export function saveStallState(s: StallState): void {
  try {
    const all = readStallStates()
    all[s.loadNumber] = s
    localStorage.setItem(LS_STALL, JSON.stringify(all))
  } catch { /* ignore */ }
}

export function getStallMinutes(loadNumber: string): number {
  try {
    const state = readStallStates()[loadNumber]
    if (!state) return 0
    return Math.floor((Date.now() - new Date(state.lastUpdateAt).getTime()) / 60000)
  } catch { return 0 }
}

// ── HOS feasibility ───────────────────────────────────────────────────────────

/**
 * How likely can the driver legally complete the remaining drive?
 * Returns 0–100 score (100 = comfortable margin, 0 = infeasible without rest).
 */
export function computeHOSFeasibility(
  driveRemHrs:    number,
  milesRemaining: number,
  avgSpeedMph:    number = 55,
): number {
  if (milesRemaining <= 0 || driveRemHrs <= 0) return 100
  const hoursNeeded = milesRemaining / avgSpeedMph

  if (hoursNeeded <= driveRemHrs * 0.60) return 100   // loads of margin
  if (hoursNeeded <= driveRemHrs * 0.75) return  85
  if (hoursNeeded <= driveRemHrs * 0.90) return  65
  if (hoursNeeded <= driveRemHrs)        return  40   // feasible but tight
  if (hoursNeeded <= driveRemHrs * 1.25) return  20   // needs a rest stop
  return 0                                             // not feasible today
}

// ── ETA confidence ────────────────────────────────────────────────────────────

export interface ETAFactors {
  estArrival?:     string    // ISO or time string
  driveRemHrs?:    number
  etaSlipMins?:    number
  weatherSevere?:  boolean
  windMph?:        number
  openEscalations?: number
}

export function computeETAConfidence(f: ETAFactors): number {
  let score = 100

  // Slip adjustment
  const slip = f.etaSlipMins ?? 0
  if      (slip >  90) score -= 45
  else if (slip >  30) score -= 25
  else if (slip >   0) score -= 10

  // HOS tightness
  const driveRem = f.driveRemHrs ?? 11
  if      (driveRem < 1.5) score -= 30
  else if (driveRem < 3.0) score -= 15

  // Weather
  if (f.weatherSevere)      score -= 25
  else if ((f.windMph ?? 0) >= 45) score -= 15
  else if ((f.windMph ?? 0) >= 30) score -=  8

  // Open critical escalations
  if ((f.openEscalations ?? 0) > 0) score -= 20

  return Math.max(0, Math.min(100, Math.round(score)))
}

// ── Weather exposure ──────────────────────────────────────────────────────────

export function computeWeatherExposure(
  severe: boolean,
  windMph: number = 0,
): number {
  if (severe)          return windMph >= 55 ? 10 : 25
  if (windMph >= 55)   return 20
  if (windMph >= 45)   return 45
  if (windMph >= 30)   return 70
  return 100
}

// ── Stall risk level ──────────────────────────────────────────────────────────

export function computeStallRisk(
  stallMinutes:  number,
  etaSlipMins?:  number,
  hasOpenCritical?: boolean,
): StallRiskLevel {
  if (hasOpenCritical)           return 'red'
  if (stallMinutes >= 60)        return 'red'
  if ((etaSlipMins ?? 0) > 90)   return 'red'
  if (stallMinutes >= 30)        return 'orange'
  if ((etaSlipMins ?? 0) > 30)   return 'orange'
  if (stallMinutes >= 20)        return 'yellow'
  if ((etaSlipMins ?? 0) > 0)    return 'yellow'
  return 'green'
}

// ── Movement score ────────────────────────────────────────────────────────────

export function computeMovementScore(stallMinutes: number): number {
  if (stallMinutes <  10) return 100
  if (stallMinutes <  20) return  90
  if (stallMinutes <  30) return  70
  if (stallMinutes <  45) return  45
  if (stallMinutes <  60) return  20
  return 0
}

// ── Overall composite score ───────────────────────────────────────────────────

function compositeScore(
  etaConf:    number,
  legalComp:  number,
  wxExp:      number,
  movement:   number,
): number {
  // weights: ETA(35%) + HOS feasibility(30%) + weather(15%) + movement(20%)
  return Math.round(etaConf * 0.35 + legalComp * 0.30 + wxExp * 0.15 + movement * 0.20)
}

function overallToStatus(score: number): LoadHealthStatus {
  if (score >= 80) return 'healthy'
  if (score >= 60) return 'monitor'
  if (score >= 40) return 'at_risk'
  return 'critical'
}

// ── Risk flag builder ─────────────────────────────────────────────────────────

function buildRiskFlags(opts: {
  stallMinutes:    number
  stallRisk:       StallRiskLevel
  etaSlipMins:     number
  driveRemHrs?:    number
  milesRemaining?: number
  weatherSevere?:  boolean
  windMph?:        number
  openCritical?:   number
  openWarning?:    number
  detentionActive?: boolean
  pmDue?:          boolean
}): RiskFlag[] {
  const flags: RiskFlag[] = []
  const {
    stallMinutes, stallRisk, etaSlipMins,
    driveRemHrs, milesRemaining,
    weatherSevere, windMph = 0,
    openCritical = 0, openWarning = 0,
    detentionActive, pmDue,
  } = opts

  // Stall flags
  if      (stallRisk === 'red')    flags.push({ type: 'stall_red',    label: 'Stall Confirmed',   severity: 'critical', value: `${stallMinutes}m ago` })
  else if (stallRisk === 'orange') flags.push({ type: 'stall_orange', label: 'Stall Likely',      severity: 'warning',  value: `${stallMinutes}m ago` })
  else if (stallRisk === 'yellow') flags.push({ type: 'stall_yellow', label: 'No Recent Update',  severity: 'warning',  value: `${stallMinutes}m ago` })

  // ETA slip
  if      (etaSlipMins > 90) flags.push({ type: 'eta_slip_major', label: 'Major ETA Slip',   severity: 'critical', value: `+${etaSlipMins}m` })
  else if (etaSlipMins > 0)  flags.push({ type: 'eta_slip',       label: 'ETA Slipping',     severity: 'warning',  value: `+${etaSlipMins}m` })

  // HOS flags
  if (driveRemHrs != null) {
    if      (driveRemHrs <= 1.5) flags.push({ type: 'hos_critical', label: 'HOS Critical',    severity: 'critical', value: `${(driveRemHrs * 60).toFixed(0)}m drive left` })
    else if (driveRemHrs <= 4.0) flags.push({ type: 'hos_risk',     label: 'HOS Risk',        severity: 'warning',  value: `${driveRemHrs.toFixed(1)}h drive left` })

    if (driveRemHrs != null && milesRemaining != null) {
      const needed = milesRemaining / 55
      if (needed > driveRemHrs) flags.push({ type: 'hos_infeasible', label: 'HOS Infeasible', severity: 'critical',
        value: `needs ${needed.toFixed(1)}h, has ${driveRemHrs.toFixed(1)}h` })
    }
  }

  // Weather
  if      (weatherSevere)  flags.push({ type: 'weather_severe', label: 'Severe Weather',    severity: 'critical' })
  else if (windMph >= 45)  flags.push({ type: 'weather_wind',   label: `High Winds ${windMph}mph`, severity: 'warning' })

  // Escalations
  if (openCritical > 0) flags.push({ type: 'escalation_critical', label: 'Critical Escalation Open', severity: 'critical', value: `${openCritical} open` })
  if (openWarning  > 0) flags.push({ type: 'escalation_warning',  label: 'Warning Escalation Open',  severity: 'warning',  value: `${openWarning} open` })

  // Other
  if (detentionActive) flags.push({ type: 'detention_running', label: 'Detention Clock Running', severity: 'warning' })
  if (pmDue)           flags.push({ type: 'pm_due',            label: 'PM Service Due',          severity: 'warning' })

  // Sort: critical first
  return flags.sort((a, b) => {
    const rank = (s: Severity) => s === 'critical' ? 0 : s === 'warning' ? 1 : 2
    return rank(a.severity) - rank(b.severity)
  })
}

// ── Recovery window generator ─────────────────────────────────────────────────

function buildRecoveryWindows(
  flags:       RiskFlag[],
  stallRisk:   StallRiskLevel,
): RecoveryWindow[] {
  const windows: RecoveryWindow[] = []
  const types = new Set(flags.map(f => f.type))

  if (stallRisk === 'red' || types.has('stall_red')) {
    windows.push({
      type: 'contact_driver', priority: 1,
      title: 'Contact Driver Now',
      description: 'No movement detected for 60+ minutes. Call driver to verify status and safety.',
      urgencyMins: 5, autoResolvable: false,
    })
  }

  if (types.has('hos_infeasible')) {
    windows.push({
      type: 'extend_delivery', priority: 2,
      title: 'Notify Customer of Delay',
      description: 'Driver cannot legally complete delivery with current HOS. Coordinate revised delivery window before cutoff.',
      urgencyMins: 30, autoResolvable: false,
    })
    windows.push({
      type: 'rest_stop', priority: 3,
      title: 'Plan Legal Rest Stop',
      description: 'Route a 10-hour rest stop en route. Resume delivery on next 11-hour clock.',
      urgencyMins: 60, autoResolvable: true,
    })
  }

  if (types.has('hos_critical')) {
    windows.push({
      type: 'contact_customer', priority: 2,
      title: 'Alert Customer — HOS Stop Imminent',
      description: 'Driver has <1.5h drive remaining. Contact receiver with updated delivery estimate.',
      urgencyMins: 15, autoResolvable: true,
    })
  }

  if (types.has('eta_slip_major')) {
    windows.push({
      type: 'contact_customer', priority: 2,
      title: 'Customer Notification Required',
      description: 'ETA has slipped 90+ minutes. Proactive contact prevents service failure claim.',
      urgencyMins: 20, autoResolvable: true,
    })
  }

  if (types.has('weather_severe')) {
    windows.push({
      type: 'reroute', priority: 3,
      title: 'Evaluate Weather Reroute',
      description: 'Severe weather on route. Check alternative corridors for safety and time efficiency.',
      urgencyMins: 30, autoResolvable: false,
    })
  }

  if (types.has('detention_running')) {
    windows.push({
      type: 'contact_customer', priority: 3,
      title: 'Escalate Detention to Receiver',
      description: 'Detention clock is running. Contact facility to expedite unloading or document for settlement.',
      urgencyMins: 30, autoResolvable: false,
    })
  }

  if (stallRisk === 'orange' || types.has('stall_orange')) {
    windows.push({
      type: 'contact_driver', priority: 2,
      title: 'Check In With Driver',
      description: '30–60 min without update. Send a check-in message to confirm movement status.',
      urgencyMins: 15, autoResolvable: true,
    })
  }

  // Deduplicate by type, keep lowest urgencyMins
  const seen = new Set<string>()
  return windows
    .sort((a, b) => a.priority - b.priority)
    .filter(w => { if (seen.has(w.type)) return false; seen.add(w.type); return true })
}

// ── Main scorer ───────────────────────────────────────────────────────────────

export interface DeriveHealthOpts {
  driveRemHrs?:    number    // from HOS data
  milesRemaining?: number
  estArrival?:     string    // ISO
  weatherSevere?:  boolean
  windMph?:        number
  pmDue?:          boolean
  avgSpeedMph?:    number
}

export function deriveLoadHealth(
  loadNumber: string,
  opts:       DeriveHealthOpts = {},
): LoadHealthScore {
  const {
    driveRemHrs,
    milesRemaining = 0,
    estArrival,
    weatherSevere = false,
    windMph = 0,
    pmDue = false,
    avgSpeedMph = 55,
  } = opts

  // Pull live dispatch data
  const updates     = readDriverUpdates(loadNumber)
  const escalations = readEscalations(loadNumber)
  const alerts      = readDispatchAlerts(loadNumber)

  // Stall minutes from saved state OR derive from most recent update
  let stallMinutes = 0
  if (updates.length > 0) {
    const lastTs = new Date(updates[0].timestamp).getTime()
    stallMinutes = Math.floor((Date.now() - lastTs) / 60000)
    // Persist stall state
    saveStallState({ loadNumber, lastUpdateAt: updates[0].timestamp })
  } else {
    stallMinutes = getStallMinutes(loadNumber)
  }

  // ETA slip
  let etaSlipMins = 0
  if (estArrival) {
    const diff = Date.now() - new Date(estArrival).getTime()
    if (diff > 0) etaSlipMins = Math.round(diff / 60000)
  }

  // Open escalation counts
  const openEsc   = escalations.filter(e => e.status === 'open' || e.status === 'owned')
  const openCrit  = openEsc.filter(e => e.severity === 'critical').length
  const openWarn  = openEsc.filter(e => e.severity === 'warning').length

  // Detention active? (detention_started but no detention_ended after it)
  const detentionActive = (() => {
    let active = false
    for (const u of updates) {
      if (u.type === 'detention_started') { active = true; break }
      if (u.type === 'detention_ended')   { active = false; break }
    }
    return active
  })()

  // Sub-scores
  const etaConf   = computeETAConfidence({
    driveRemHrs, etaSlipMins, weatherSevere, windMph,
    openEscalations: openCrit,
  })
  const legalComp = (driveRemHrs != null && milesRemaining > 0)
    ? computeHOSFeasibility(driveRemHrs, milesRemaining, avgSpeedMph)
    : 85   // unknown → optimistic default

  const wxExp      = computeWeatherExposure(weatherSevere, windMph)
  const movement   = computeMovementScore(stallMinutes)

  // Composite — also penalise for critical escalations
  let overall = compositeScore(etaConf, legalComp, wxExp, movement)
  if (openCrit > 0) overall = Math.max(0, overall - 20)
  if (openWarn > 0) overall = Math.max(0, overall - 10)

  const status     = overallToStatus(overall)
  const stallRisk  = computeStallRisk(stallMinutes, etaSlipMins, openCrit > 0)

  // ETA re-estimate
  let projectedArrival: string | null = null
  if (estArrival && (etaSlipMins > 0 || stallMinutes > 30)) {
    const base    = new Date(estArrival).getTime()
    const slipMs  = etaSlipMins * 60000
    const stallMs = stallMinutes > 30 ? (stallMinutes - 20) * 60000 : 0
    projectedArrival = new Date(base + slipMs + stallMs).toISOString()
  }

  const riskFlags = buildRiskFlags({
    stallMinutes, stallRisk, etaSlipMins, driveRemHrs, milesRemaining,
    weatherSevere, windMph, openCritical: openCrit, openWarning: openWarn,
    detentionActive, pmDue,
  })

  const recoveryWindows = buildRecoveryWindows(riskFlags, stallRisk)

  const score: LoadHealthScore = {
    loadNumber,
    etaConfidence:   etaConf,
    legalCompletion: legalComp,
    weatherExposure: wxExp,
    movementScore:   movement,
    overall,
    status,
    stallRisk,
    stallMinutes,
    riskFlags,
    recoveryWindows,
    etaSlipMins,
    projectedArrival,
    snapshot: new Date().toISOString(),
  }

  // Persist snapshot
  saveHealthSnapshot(score)

  // Log critical transitions to unified ops event log
  const prev = getLastHealthSnapshot(loadNumber)
  if (status === 'critical' && prev?.status !== 'critical') {
    logLoadHealthEvent({
      eventType:  'load_health_critical',
      loadNumber,
      title:      `Load #${loadNumber} entered CRITICAL health — score ${overall}`,
      body:       riskFlags.filter(f => f.severity === 'critical').map(f => f.label).join(', ') || undefined,
      score:      overall,
    })
  } else if (status === 'healthy' && (prev?.status === 'critical' || prev?.status === 'at_risk')) {
    logLoadHealthEvent({
      eventType:  'load_health_recovered',
      loadNumber,
      title:      `Load #${loadNumber} recovered — score ${overall}`,
      score:      overall,
    })
  } else if (stallRisk !== 'green' && prev?.stallRisk === 'green') {
    logOpsEvent({
      eventType:    'exception_logged',
      severity:     stallRisk === 'red' || stallRisk === 'orange' ? 'critical' : 'warning',
      loadNumber,
      sourceEngine: 'load_health_engine',
      title:        `Stall risk elevated to ${stallRisk.toUpperCase()} — ${stallMinutes}m`,
    })
  }

  return score
}

// ── Snapshot persistence ──────────────────────────────────────────────────────

export function readHealthSnapshots(): LoadHealthScore[] {
  try { return JSON.parse(localStorage.getItem(LS_HEALTH) ?? '[]') }
  catch { return [] }
}

export function saveHealthSnapshot(score: LoadHealthScore): void {
  try {
    const all = readHealthSnapshots()
    const idx = all.findIndex(s => s.loadNumber === score.loadNumber)
    if (idx >= 0) all[idx] = score
    else all.unshift(score)
    localStorage.setItem(LS_HEALTH, JSON.stringify(all.slice(0, MAX_HEALTH)))
  } catch { /* storage full */ }
}

export function getLastHealthSnapshot(loadNumber: string): LoadHealthScore | null {
  return readHealthSnapshots().find(s => s.loadNumber === loadNumber) ?? null
}

// ── Exception timeline ────────────────────────────────────────────────────────

export function readExceptions(loadNumber?: string): ExceptionEvent[] {
  try {
    const all: ExceptionEvent[] = JSON.parse(localStorage.getItem(LS_EXCEPTIONS) ?? '[]')
    return loadNumber ? all.filter(e => e.loadNumber === loadNumber) : all
  } catch { return [] }
}

export function logException(exc: Omit<ExceptionEvent, 'id' | 'timestamp'>): ExceptionEvent {
  const event: ExceptionEvent = {
    ...exc,
    id:        crypto.randomUUID(),
    timestamp: new Date().toISOString(),
  }
  try {
    const all = readExceptions()
    all.unshift(event)
    localStorage.setItem(LS_EXCEPTIONS, JSON.stringify(all.slice(0, MAX_EXCEPTIONS)))
  } catch { /* storage full */ }
  return event
}

export function resolveException(id: string, resolution: string): void {
  try {
    const all = readExceptions()
    const idx = all.findIndex(e => e.id === id)
    if (idx >= 0) {
      all[idx] = { ...all[idx], resolvedAt: new Date().toISOString(), resolution }
      localStorage.setItem(LS_EXCEPTIONS, JSON.stringify(all.slice(0, MAX_EXCEPTIONS)))
    }
  } catch { /* ignore */ }
}

/**
 * Auto-generate exception events from a health score change.
 * Call this whenever you derive a new health score — it will
 * log new critical/warning flags that weren't already logged.
 */
export function syncExceptionsFromHealth(score: LoadHealthScore): void {
  const existing = readExceptions(score.loadNumber)
  const existingTypes = new Set(
    existing.filter(e => !e.resolvedAt).map(e => e.type)
  )

  for (const flag of score.riskFlags) {
    if (flag.severity === 'info') continue       // skip info-level
    if (existingTypes.has(flag.type)) continue   // already logged

    logException({
      loadNumber:    score.loadNumber,
      type:          flag.type,
      title:         flag.label,
      body:          flag.value
        ? `${flag.label} — ${flag.value}`
        : `${flag.label} detected on Load #${score.loadNumber}`,
      escalated:     flag.severity === 'critical',
      autoGenerated: true,
    })
  }

  // Auto-resolve stall exceptions that recovered
  if (score.stallRisk === 'green') {
    const stallExceptions = existing.filter(
      e => !e.resolvedAt && (e.type === 'stall_red' || e.type === 'stall_orange' || e.type === 'stall_yellow')
    )
    for (const e of stallExceptions) {
      resolveException(e.id, 'Driver resumed movement — stall auto-resolved')
    }
  }
}

// ── Fleet-level summary ───────────────────────────────────────────────────────

export interface FleetHealthSummary {
  totalLoads:   number
  healthy:      number
  monitor:      number
  atRisk:       number
  critical:     number
  activeStalls: number
  avgScore:     number
  topFlag:      RiskFlag | null
}

export function buildFleetHealthSummary(scores: LoadHealthScore[]): FleetHealthSummary {
  if (scores.length === 0) {
    return { totalLoads: 0, healthy: 0, monitor: 0, atRisk: 0, critical: 0, activeStalls: 0, avgScore: 0, topFlag: null }
  }
  const counts = { healthy: 0, monitor: 0, at_risk: 0, critical: 0 }
  let totalScore = 0
  let activeStalls = 0
  const flagMap = new Map<RiskFlagType, RiskFlag & { count: number }>()

  for (const s of scores) {
    counts[s.status]++
    totalScore += s.overall
    if (s.stallRisk === 'orange' || s.stallRisk === 'red') activeStalls++
    for (const f of s.riskFlags) {
      const existing = flagMap.get(f.type)
      if (existing) existing.count++
      else flagMap.set(f.type, { ...f, count: 1 })
    }
  }

  // Top flag = most-flagged critical issue
  const allFlags = [...flagMap.values()].sort((a, b) => {
    const rank = (s: Severity) => s === 'critical' ? 0 : 1
    return rank(a.severity) - rank(b.severity) || b.count - a.count
  })

  return {
    totalLoads:  scores.length,
    healthy:     counts.healthy,
    monitor:     counts.monitor,
    atRisk:      counts.at_risk,
    critical:    counts.critical,
    activeStalls,
    avgScore:    Math.round(totalScore / scores.length),
    topFlag:     allFlags[0] ?? null,
  }
}

// ── Display helpers ───────────────────────────────────────────────────────────

export function healthScoreColor(score: number): string {
  if (score >= 80) return 'var(--primary)'
  if (score >= 60) return 'var(--warn)'
  if (score >= 40) return '#f97316'
  return 'var(--error)'
}

export function stallTimeLabel(minutes: number): string {
  if (minutes < 1)  return 'just now'
  if (minutes < 60) return `${minutes}m ago`
  const h = Math.floor(minutes / 60), m = minutes % 60
  return m > 0 ? `${h}h ${m}m ago` : `${h}h ago`
}

export function recoveryUrgencyLabel(mins: number): string {
  if (mins <= 5)  return 'Act immediately'
  if (mins <= 15) return 'Act within 15 min'
  if (mins <= 30) return 'Act within 30 min'
  if (mins <= 60) return 'Act within 1 hour'
  return 'Plan required'
}
