'use client'
/**
 * ExceptionTimeline — DispatchOps AI v2
 *
 * Chronological log of load health exceptions (auto-generated + manual).
 * Supports inline resolution with a one-line note.
 */
import { useState } from 'react'
import {
  type ExceptionEvent,
  readExceptions,
  resolveException,
} from '@/lib/loadHealthEngine'

function timeAgo(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 1)  return 'just now'
  if (mins < 60) return `${mins}m ago`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24)  return `${hrs}h ago`
  return `${Math.floor(hrs / 24)}d ago`
}

const FLAG_EMOJI: Record<string, string> = {
  eta_slip:              '⏱',
  eta_slip_major:        '⏱',
  hos_critical:          '🛑',
  hos_risk:              '⏳',
  stall_yellow:          '🟡',
  stall_orange:          '🟠',
  stall_red:             '🔴',
  weather_severe:        '⛈',
  weather_wind:          '💨',
  no_updates:            '📵',
  detention_running:     '⏸',
  pm_due:                '🔧',
  escalation_critical:   '🚨',
  escalation_warning:    '⚠️',
  hos_infeasible:        '🚫',
}

interface ExceptionRowProps {
  exc:       ExceptionEvent
  onResolve: (id: string, resolution: string) => void
}

function ExceptionRow({ exc, onResolve }: ExceptionRowProps) {
  const [resolving, setResolving] = useState(false)
  const [note,      setNote]      = useState('')
  const [done,      setDone]      = useState(false)

  const handleResolve = () => {
    if (!note.trim()) return
    onResolve(exc.id, note.trim())
    setDone(true)
    setResolving(false)
  }

  const resolved = !!exc.resolvedAt || done
  const emoji    = FLAG_EMOJI[exc.type] ?? '📋'
  const color    = exc.escalated ? 'var(--error)' : 'var(--warn)'
  const bg       = exc.escalated ? 'rgba(232,64,0,.06)' : 'rgba(245,194,0,.05)'
  const border   = exc.escalated ? 'rgba(232,64,0,.18)' : 'rgba(245,194,0,.18)'

  return (
    <div style={{
      padding: '.65rem .85rem', borderRadius: 10,
      background: resolved ? 'var(--surface-2)' : bg,
      border: `1px solid ${resolved ? 'var(--border)' : border}`,
      opacity: resolved ? .65 : 1,
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 3 }}>
            <span style={{ fontSize: '.85rem' }}>{emoji}</span>
            <span style={{ fontWeight: 800, fontSize: '.72rem', color: resolved ? 'var(--muted)' : color }}>
              {exc.title}
            </span>
            {exc.escalated && !resolved && (
              <span style={{
                fontSize: '.55rem', fontWeight: 800, color: 'var(--error)',
                padding: '.1rem .4rem', borderRadius: 8,
                background: 'rgba(232,64,0,.1)', border: '1px solid rgba(232,64,0,.2)',
              }}>
                ESCALATED
              </span>
            )}
            {exc.autoGenerated && (
              <span style={{
                fontSize: '.55rem', fontWeight: 700, color: 'var(--muted)',
                padding: '.1rem .4rem', borderRadius: 8, background: 'var(--surface-2)',
              }}>
                AI
              </span>
            )}
          </div>
          <div style={{ fontSize: '.65rem', color: 'var(--muted)', lineHeight: 1.5 }}>{exc.body}</div>
          {resolved && exc.resolution && (
            <div style={{ fontSize: '.62rem', color: 'var(--primary)', marginTop: 3, fontWeight: 700 }}>
              ✅ {exc.resolution}
            </div>
          )}
        </div>
        <div style={{ textAlign: 'right', flexShrink: 0 }}>
          <div style={{ fontSize: '.58rem', color: 'var(--muted)', marginBottom: 4 }}>
            {timeAgo(exc.timestamp)}
          </div>
          {!resolved && !resolving && (
            <button
              onClick={() => setResolving(true)}
              style={{
                padding: '.2rem .55rem', borderRadius: 7, fontSize: '.6rem', fontWeight: 800,
                border: '1px solid var(--border)', background: 'var(--surface)',
                color: 'var(--text)', cursor: 'pointer',
              }}
            >
              Resolve
            </button>
          )}
        </div>
      </div>

      {resolving && (
        <div style={{ marginTop: '.6rem', display: 'flex', gap: 6 }}>
          <input
            value={note}
            onChange={e => setNote(e.target.value)}
            placeholder="Resolution note…"
            autoFocus
            onKeyDown={e => { if (e.key === 'Enter') handleResolve() }}
            style={{
              flex: 1, padding: '.35rem .65rem', borderRadius: 7,
              border: '1px solid var(--border)', background: 'var(--surface-2)',
              color: 'var(--text)', fontSize: '.65rem', outline: 'none',
            }}
          />
          <button
            onClick={handleResolve}
            disabled={!note.trim()}
            style={{
              padding: '.35rem .7rem', borderRadius: 7, fontWeight: 800, fontSize: '.65rem',
              border: 'none', cursor: note.trim() ? 'pointer' : 'not-allowed',
              background: note.trim() ? 'rgba(0,232,176,.15)' : 'var(--surface-2)',
              color: note.trim() ? 'var(--primary)' : 'var(--muted)',
            }}
          >
            Save
          </button>
          <button
            onClick={() => setResolving(false)}
            style={{
              padding: '.35rem .5rem', borderRadius: 7, fontSize: '.65rem',
              border: '1px solid var(--border)', background: 'transparent',
              color: 'var(--muted)', cursor: 'pointer',
            }}
          >
            ✕
          </button>
        </div>
      )}
    </div>
  )
}

// ── Main component ────────────────────────────────────────────────────────────

interface Props {
  loadNumber?: string    // if omitted, shows all loads
  maxItems?:  number
}

export default function ExceptionTimeline({ loadNumber, maxItems = 20 }: Props) {
  const [exceptions, setExceptions] = useState<ExceptionEvent[]>(() =>
    readExceptions(loadNumber).slice(0, maxItems)
  )
  const [showResolved, setShowResolved] = useState(false)

  const handleResolve = (id: string, resolution: string) => {
    resolveException(id, resolution)
    setExceptions(readExceptions(loadNumber).slice(0, maxItems))
  }

  const visible   = showResolved ? exceptions : exceptions.filter(e => !e.resolvedAt)
  const resolvedN = exceptions.filter(e => !!e.resolvedAt).length

  if (exceptions.length === 0) {
    return (
      <div style={{
        padding: '.75rem .9rem', borderRadius: 10,
        background: 'rgba(0,232,176,.05)', border: '1px solid rgba(0,232,176,.15)',
        fontSize: '.68rem', fontWeight: 700, color: 'var(--primary)',
        display: 'flex', alignItems: 'center', gap: 8,
      }}>
        ✅ No exceptions logged{loadNumber ? ` for Load #${loadNumber}` : ''} — system nominal
      </div>
    )
  }

  return (
    <div style={{ display: 'grid', gap: '.45rem' }}>
      {/* Header row */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '.15rem' }}>
        <div style={{ fontSize: '.6rem', fontWeight: 800, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '.1em' }}>
          📋 Exception Log
          {loadNumber ? ` — Load #${loadNumber}` : ''}
        </div>
        {resolvedN > 0 && (
          <button
            onClick={() => setShowResolved(v => !v)}
            style={{
              fontSize: '.6rem', fontWeight: 700, color: 'var(--muted)',
              background: 'none', border: 'none', cursor: 'pointer', textDecoration: 'underline',
            }}
          >
            {showResolved ? 'Hide' : 'Show'} {resolvedN} resolved
          </button>
        )}
      </div>

      {visible.length === 0 && (
        <div style={{ fontSize: '.65rem', color: 'var(--muted)', padding: '.5rem .65rem', background: 'var(--surface-2)', borderRadius: 8, border: '1px solid var(--border)' }}>
          All exceptions resolved.
        </div>
      )}

      {visible.map(exc => (
        <ExceptionRow key={exc.id} exc={exc} onResolve={handleResolve} />
      ))}
    </div>
  )
}
